baseURL: "https://blog.toddaas.com/"
title: toddaas
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: UA-123-45

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: toddaas
    description: "toddaas"
    keywords: [blog, toddaas]
    author: Todd
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: true

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    label:
        text: " "

    assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        favicon: "<link / abs url>"
        favicon16x16: "<link / abs url>"
        favicon32x32: "<link / abs url>"
        apple_touch_icon: "<link / abs url>"
        safari_pinned_tab: "<link / abs url>"

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: "Todd Bryant"
        subtitle: "A cloud (network) engineer based in Sydney, Australia."
        imageUrl: "/img/570243.jpg"
        imageWidth: 120
        imageHeight: 120
        imageTitle: This is me
        buttons:
            - name: Posts
              url: posts
        

    # home-info mode
    homeInfoParams:
        Title: "Gday, \U0001F44B"
        Content: Welcome to the learnings of a cloud (network) engineer based in Sydney, Australia.

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/bryanttodd/"
        - name: github
          url: "https://github.com/toddsfish"
        - name: other
          url: "https://toddaas-aueast-prod-shaarli.azurewebsites.net/"
        - name: twitter
          url: "https://twitter.com/toomanytodds"
        - name: instagram
          url: "https://instagram.com/tt0odd"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    editPost:
        URL: "https://github.com/toddsfish/toddaas-blog/tree/master/content/"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: home
          name: home
          url: /
          weight: 10
        - identifier: posts
          name: posts
          url: /posts/
          weight: 20
        - identifier: tags
          name: tags
          url: /tags/
          weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai